#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'insertionSort1' function below.
#
# The function accepts following parameters:
#  1. INTEGER n
#  2. INTEGER_ARRAY arr
#


def insertionSort1(n, arr):
    # Write your code here
    n = len(arr)
    last = arr[n-1]
    for i in range(n-2, -1, -1):
        if i==0 and last<arr[i]:
            arr[i+1] = arr[i]
            print(" ".join(map(str, arr)))
            arr[i] =last  
        elif last < arr[i]:
            arr[i+1] = arr[i]
            print(" ".join(map(str, arr)))
        
        elif last >= arr[i]:
            arr[i+1] = last
            break
    print(" ".join(map(str, arr)))



if __name__ == '__main__':
    n = int(input().strip())

    arr = list(map(int, input().rstrip().split()))

    insertionSort1(n, arr)
